# Generated by Django 3.2.4 on 2021-07-04 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='i', max_length=1)),
                ('cadastro', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entrada', models.CharField(choices=[('M', 'Mensalista'), ('A', 'Avulso'), ('E', 'Especial')], max_length=1)),
                ('tipo_veiculo', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Medio'), ('G', 'Grande'), ('C', 'Carreta'), ('B', 'Bi-trem'), ('A', 'Cavalo')], max_length=1)),
                ('placa', models.CharField(max_length=7)),
                ('data', models.DateTimeField()),
                ('status_patio', models.CharField(choices=[('N', 'Nulo'), ('P', 'Patio'), ('L', 'Livre'), ('B', 'Bloqueado'), ('E', 'Espera')], max_length=1)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=15, null=True)),
                ('cor', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Medio'), ('G', 'Grande'), ('C', 'Carreta'), ('B', 'Bi-trem'), ('A', 'Cavalo')], max_length=1)),
                ('placa', models.CharField(max_length=7)),
                ('cadastro', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('id_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.cliente')),
            ],
        ),
    ]
